### ISSUE TITLE
[DUPE] Conflict with mcmmo

### ISSUE THREAD

**Issue by mani1232** [Auxilor/EcoEnchants#41] opened 2021-03-19 15:44 UTC
If your level of mining allows you to get a double, triple drop, then you can put some kind of object over a block of ore or stone that drops out if you break a block under it and they become 2 or 3

Core version: 1.16.5 (Yatopia or papermc) 
Plugin version: 6.10.6

**Comment by mani1232** [comment] 2021-03-21 07:35
Still not fixed

Core version: 1.16.5 (Yatopia)
Plugin version: 6.10.7

**Comment by DeZoWaRe** [comment] 2021-04-17 14:32
The author doesn't give a fuck, he didn't even fix the dupe of the experience with curses

**Comment by Auxilor** [comment] 2021-04-17 14:33
> The author doesn't give a fuck, he didn't even fix the dupe of the experience with curses

what the fuck is your problem?

Also - ask for support on my [discord](https://discord.gg/ZcwpSsE), I don't check github issues :)

**Closed by Auxilor** 2021-04-17 14:33 UTC
